### ISSUE TITLE
How to use this plugin ?

### ISSUE THREAD

**Issue by Ajinkz** [zokis/SpotifySublime#3]

**Comment by zokis** [comment]
install via: https://packagecontrol.io/packages/SpotifyPlayer%20(Ubuntu)

use the following commands from command palette: 

- Spotify: Play
- Spotify: Pause
- Spotify: Next
- Spotify: Previous
- Spotify: Stop
- Volume: Up
- Volume: Down
- Volume: Set

**Comment by Ajinkz** [comment]
Sorry, I was unable to use these command
